import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import bob from "../public/bob.svg";

const myFont = localFont({
  src: [
    {
      path: "./TTTravels-Bold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "./TTTravels-DemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./TTTravels-Italic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        {children}
        <Image
          src={bob}
          alt="bob"
          width={580}
          height={520}
          className="fixed bottom-0 right-0"
          placeholder="blur"
        />
      </body>
    </html>
  );
}
